apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v2
  template:
    metadata:
      labels:
        app: web
        version: v2
    spec:
      containers:
      - image: envweb:v1
        imagePullPolicy: IfNotPresent
        name: envweb
        env:
        - name: MSG
          value: This app is version 2
        ports:
        - containerPort: 8080
